### ISSUE TITLE
Instant Kill

### ISSUE THREAD

**Issue by saboteur13** [d3xter-dev/dayz-class-selection#4]
Hi LemmingTV

As discussed on Steam chat yesterday, please see attached:
Class Selection Profiles Folder
init.c file

Let me know if you require anything else.
[ClassSelection.zip](https://github.com/d3xter-dev/dayz-class-selection/files/5678363/ClassSelection.zip)
[init.zip](https://github.com/d3xter-dev/dayz-class-selection/files/5678364/init.zip)

Best,
JaNeeKyk

**Comment by d3xter-dev** [comment]
Hey I had finally time to look into your problem, 
you set "showClassSelectOnRespawnOnly"  which forces the player to select a class everytime they die, but in order to receive the items he has to die again, so he gets instant killed ... 
better solution for you would be setting showClassSelectOnRespawnOnly to 0 and giveWeaponsAfterDeath to 1
so players can choose a class whenever they want but will receive the items next time they die. 
(also as player I would be annoyed AF when I have to select a class each time i die)
